version: '3.4'
services:
  web:
    build: docker/apache
    container_name: ${PROJECT_NAME}_web
    volumes:
# les fichiers du site seront à placer dans le dossier web suivi du nom du projet
     - ./web_${PROJECT_NAME}:${PROJECT_PATH}:cached
     - ./docker/apache/sites_enabled:/etc/apache2/sites_enabled
     - ./docker/php/custom-php.ini:/use/local/etc/php/conf.d/custom-php.ini
#     - ./docker/apache/conf:/etc/apache2/conf
    depends_on:
     - db
    ports:
     - "8082:80"
#     - "443:443"
  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: ${PROJECT_NAME}_mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # on pourra utiliser le user user
      MYSQL_USER: ${MYSQL_USER_NAME}
      # le mdp password
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      # le password pour le root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
# Modif limite upload pour les bdd importees
      UPLOAD_LIMIT: 20M
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
      # Where our data will be persisted
    volumes:
      #- ./docker/db/custom.cnf:/etc/mysql/conf.d/custom.cnf:cached
      #- ./db_data:/var/lib/mysql:cached
      - ./docker/db/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./db_data:/var/lib/mysql      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_pma
    depends_on:
     - db
    ports:
     - "8083:80"
    environment:
     - PMA_HOST=db
# Modif limite upload pour les bdd importees
     - UPLOAD_LIMIT="20M"
#     - PMA_USER=root
#     - PMA_PASSWORD=root

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge





# Names our volume
volumes:
  db_data:
  postgres:
  pgadmin:
